# fly.toml app configuration file generated for sshx-enview on 2024-01-19T11:10:18+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sshx-enview"
primary_region = "ewr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["sh", "-c", "./sshx-server --listen :: --host \"$FLY_ALLOC_ID.vm.sshx.internal:8051\""]
  auto_rollback = true

[build]

[http_service]
  internal_port = 8051
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8051
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls"]
    [services.ports.tls_options]
      alpn = ["h2", "http/1.1"]
  [services.concurrency]
    type = "connections"
    hard_limit = 65536
    soft_limit = 1024

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
